### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by gala0sup** [gala0sup/RLMA#1]
* [ ] core
  * [ ] Library
    * [ ] Library
      * [ ] fix `_ok_categoriesDialog`
      * [ ] add preview in `add_item_dialog`
      * [ ] fix `a.ids.drop_item.set_item(instance.text)` Updating of ItemType when adding a New Item
      * [ ] Complete saving and retrival of Library
    * [ ] LibraryItem
      * [ ] Saving and retrieval of Library item
      * [ ] Download and save `Scraper.about` when adding new Items
      * [ ] fix 403 error when downloading image
